### ISSUE TITLE
Please publish docker image on a public docker registry, like Docker Hub or GitHub Container Registry

### ISSUE THREAD

**Issue by ryboe** [ajmwagar/merino#37]
I would like to use merino on [Google Container-Optimized OS](https://cloud.google.com/container-optimized-os/docs), which is a hardened distro that only runs containers. It would be nice if I didn't have to build the merino image myself. I looked at the Dockerfile you already have and it LGTM 🙂👍 Can you please publish the image on a public docker registry, like Docker Hub or GitHub Container Registry? 🙏 

Here's a GitHub workflow I use to publish one of my images to GHCR.

```yaml
name: Release

on:
  push:
    branches:
      - master

jobs:
  build_and_upload_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          # mode=max means "cache everything possible". This ensures maximum
          # use of the cache, but will use up GitHub's 10 GB cache size limit
          # faster.
          cache-to: type=gha,mode=max
```

This is using the latest GitHub+docker buildx features to build the image as quickly as possible (using layer caching provided by GitHub Actions).

I'd be happy to submit this as an PR, along with some README instructions about how to `docker pull` the image.
